FROM registry.access.redhat.com/ubi9/ubi-minimal

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /opt/app-root/src 

RUN microdnf -y install python3.12 \
&& microdnf -y install python3.12-pip \
&& microdnf clean all

COPY app.py requirements.txt .

RUN pip3.12 install --upgrade pip \
  && pip3.12 install -r requirements.txt \
  && pip3.12 cache purge

ENV GRADIO_SERVER_NAME="0.0.0.0"

# This is primarily a reminder that we need access to port 7860
EXPOSE 7860

CMD ["python3.12", "app.py"]
